### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by aeharding** [bikerglen/bicycle-traffic-signal#1]
Hello!

I've printed this out with Multi-Jet and a Prusa Mini+. It looks great with both!

I'd love if there was a license associated with this project. I'd like to remix the design that's more compatible with traditional/cheaper 3d printers (easier overhangs to mitigate supports) and share the design with others.

Would you consider adding an MIT license or another open source license?

![IMG_1478](https://user-images.githubusercontent.com/2166114/135286526-0444b895-f44b-4d49-bc90-5025362871d2.jpg)

Thank you
Alex

**Comment by bikerglen** [comment]
That's awesome! Agreed, having a version that has better compatibility with lower-cost popular printers would be great. I'll add the MIT license this afternoon.

**Comment by aeharding** [comment]
Thanks for adding the license! I'll close this. Also, I see `halloween-hazards` in the repo - not sure if that was meant to be added :-)

**Comment by bikerglen** [comment]
No problem. The Halloween hazards are some alternate stickers if someone wants to make a radiation/poison/biological hazard warning sign for their zombie lab this month. Enjoy and I'm looking forward to seeing your mods!
